### ISSUE TITLE
Bridge doesn't start after upgrade to 0.1.2 - AttributeError: '_Union' object has no attribute 'deserialize'

### ISSUE THREAD

**Issue by Georg311** [tulir/mautrix-hangouts#35]
After Upgrading the bridge to the latest version following error appears when try to start or upgrade the bridge
```python
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/mautrix-hangouts/lib/python3.6/site-packages/mautrix_hangouts/__main__.py", line 16, in <module>
    from mautrix.bridge import Bridge
  File "/opt/mautrix-hangouts/lib/python3.6/site-packages/mautrix/bridge/__init__.py", line 2, in <module>
    from .custom_puppet import CustomPuppetMixin, CustomPuppetError, OnlyLoginSelf, InvalidAccessToken
  File "/opt/mautrix-hangouts/lib/python3.6/site-packages/mautrix/bridge/custom_puppet.py", line 17, in <module>
    from mautrix.types import (UserID, FilterID, Filter, RoomEventFilter, RoomFilter, EventFilter,
  File "/opt/mautrix-hangouts/lib/python3.6/site-packages/mautrix/types/__init__.py", line 3, in <module>
    from .filter import Filter, EventFilter, RoomFilter, StateFilter, RoomEventFilter
  File "/opt/mautrix-hangouts/lib/python3.6/site-packages/mautrix/types/filter.py", line 10, in <module>
    from .event import EventType
  File "/opt/mautrix-hangouts/lib/python3.6/site-packages/mautrix/types/event/__init__.py", line 15, in <module>
    from .state import (PowerLevelStateEventContent, Membership, MemberStateEventContent, StateEvent,
  File "/opt/mautrix-hangouts/lib/python3.6/site-packages/mautrix/types/event/state.py", line 13, in <module>
    from .encrypted import EncryptionAlgorithm
  File "/opt/mautrix-hangouts/lib/python3.6/site-packages/mautrix/types/event/encrypted.py", line 89, in <module>
    setattr(EncryptedEventContent, "deserialize", deserialize_encrypted)
AttributeError: '_Union' object has no attribute 'deserialize'

```

Any Idea what I should do?

I tried to adapt the config to the latest example config, so that no parameters are missing, which should now be the case.
I'm not trying to use bridge encryption, if that helps

**Comment by tulir** [comment]
Looks like I accidentally broke Python 3.6 compatibility at some point, but I already stopped officially supporting it (I only support latest Debian and Ubuntu LTS), so not sure if I'm going to fix that. 3.7+ should work

**Comment by Georg311** [comment]
Thanks that did the trick.
On Centos I've only got older Python versions, so i had to compile it myself - works now.
